name: aura_plus
description: Interactive Language Therapy Application Using Surface-Based AR and AI Recommendation System for Children with Autism Spectrum Disorder (ASD)

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  
  # Routing
  go_router: ^16.2.1
  
  # Backend & Auth
  supabase_flutter: ^2.0.0
  
  # Utilities
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  dio: ^5.3.2
  
  # UI/UX
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  lottie: ^3.3.2

  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^3.0.0-dev.17
  freezed: ^3.2.0
  json_serializable: ^6.7.1

  arcore_flutter_plugin: ^0.1.0
  arkit_plugin: ^1.2.1
  permission_handler: ^12.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
    - assets/audio/
    - assets/unity/
    - assets/therapy_content/